### ISSUE TITLE
Exception for the if condition in Minimizer.cpp Line 231

### ISSUE THREAD

**Issue by Teddym0913** [phbasler/BSMPT#1]
Dear authors:
   It seem the condition in that if statement is not correct.

As only when vevsolTmp <=0.5 (actually 0) the ModifiedVEVVectorDim has a size of nVEV. However that condition allows vevsolTmp > 0.5 when MinZero is 1, which will result in a segmentation fault. 

The exception input is:
1	0.258106	0.258106	0.258106	0	0	369562	2

Please have check! 
And Thanks for sharing this program.

**Comment by phbasler** [comment]
Thanks for the response and for also writing this to me via email. This issue was fixed with the update at 2018/03/30
