### ISSUE TITLE
Installation error in default mode

### ISSUE THREAD

**Issue by CodePrO51** [phbasler/BSMPT#143]
I am trying to to install on MacOS in default settings via build.py scripts. It gives an error -

clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/benchmarks] Error 1
make[1]: *** [tests/benchmarks/CMakeFiles/benchmarks.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 68%] Linking CXX static library libMinimumTracer.a
[ 68%] Built target MinimumTracer
make: *** [all] Error 2
Traceback (most recent call last):
  File "/Users/harshaggarwal/Desktop/BSMPT/BSMPT/Build.py", line 36, in <module>
    main()
  File "/Users/harshaggarwal/Desktop/BSMPT/BSMPT/Build.py", line 33, in main
    build(get_preset())
  File "/Users/harshaggarwal/Desktop/BSMPT/BSMPT/Build.py", line 27, in build
    subprocess.check_call(cmd)
  File "/Users/harshaggarwal/anaconda3/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '--preset', 'conan-macos-armv8-release']' returned non-zero exit status 2.

Please let me know if there is any solution to this.

**Comment by phbasler** [comment]
Hi,

Which compiler and version are you using?

**Comment by CodePrO51** [comment]
I am uisng Clang version 15.0.0

**Comment by phbasler** [comment]
Can you run `conan profile detect`  or `conan profile show` if the detect command fails and copy the output?

**Comment by CodePrO51** [comment]
Thank you for your response. I think it runs fine:

detect_api: Found apple-clang 15.0

detect_api: apple-clang>=13, using the major as version


*Detected profile:*

[settings]

arch=armv8

build_type=Release

compiler=apple-clang

compiler.cppstd=gnu17

compiler.libcxx=libc++

compiler.version=15

os=Macos


WARN: This profile is a guess of your environment, please check it.

WARN: Defaulted to cppstd='gnu17' for apple-clang.

WARN: The output of this command is not guaranteed to be stable and can
change in future Conan versions.

WARN: Use your own profile files for stability.

*Saving detected profile to /Users/harshaggarwal/.conan2/profiles/default*

**Comment by phbasler** [comment]
Can you change `compiler.version=13` in `profiles/BSMPT/macos-release-armv8` to `compiler.version=15` , remove the `build` folder and try the script again?

**Comment by CodePrO51** [comment]
I tried that. I am getting the same error -

ld: warning: ignoring duplicate libraries: '-lc++',
'../../src/ThermalFunctions/libThermalFunctions.a',
'../../src/minimizer/libMinimizer.a', '../../src/models/libModels.a',
'../../src/utility/libUtility.a'

ld: Undefined symbols:

  benchmark::Initialize(int*, char**), referenced from:

      _main in benchmark-ewpt-c2hdm.cpp.o

clang: *error: **linker command failed with exit code 1 (use -v to see
invocation)*

make[2]: *** [bin/benchmarks] Error 1

make[1]: *** [tests/benchmarks/CMakeFiles/benchmarks.dir/all] Error 2

make[1]: *** Waiting for unfinished jobs....

[ 68%] *Linking CXX static library libMinimumTracer.a*

[ 68%] Built target MinimumTracer

make: *** [all] Error 2

Traceback (most recent call last):

  File "/Users/harshaggarwal/Desktop/BSMPT/BSMPT/Build.py", line 36, in
<module>

    main()

  File "/Users/harshaggarwal/Desktop/BSMPT/BSMPT/Build.py", line 33, in main

    build(get_preset())

  File "/Users/harshaggarwal/Desktop/BSMPT/BSMPT/Build.py", line 27, in
build

    subprocess.check_call(cmd)

  File "/Users/harshaggarwal/anaconda3/lib/python3.11/subprocess.py", line
413, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['cmake', '--build', '--preset',
'conan-macos-armv8-release']' returned non-zero exit status 2.

**Comment by CodePrO51** [comment]
Hi, I was able to install it. There seemed to be some issue due to conda. I
used conda deactivate and it worked after that. I have faced this problem
with Conda earlier as well.
Thanks for your help.

Regards,
Harsh

**Comment by CodePrO51** [comment]
I had to modify the profile to version 15.
