### ISSUE TITLE
Make error with NLopt

### ISSUE THREAD

**Issue by phyzhangyang** [phbasler/BSMPT#24]
Dear all,

I encountered some errors when I compiled BSMPT2 on macOS. 

The first error is 
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:1547:38: error: 
      implicit instantiation of undefined template 'std::__1::hash<BSMPT::ModelID::ModelIDs>'
    : public integral_constant<bool, __is_empty(_Tp)> {};
```
which can be fixed by adding 
```
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
to cmake file.

Then I got
```
/Users/zhangyang/work/PhaseTracer/BSMPT-master/include/BSMPT/minimizer/LibNLOPT/MinimizeNLOPT.h:6:10: fatal error: 
      'nlopt.hpp' file not found
#include <nlopt.hpp>
         ^~~~~~~~~~~
/Users/zhangyang/work/PhaseTracer/BSMPT-master/src/minimizer/MinimizeGSL.cpp:29:10: fatal error: 
      'ext/alloc_traits.h' file not found
#include <ext/alloc_traits.h>                   // for __alloc_traits<>::val...
         ^~~~~~~~~~~~~~~~~~~~
/Users/zhangyang/work/PhaseTracer/BSMPT-master/src/minimizer/MinimizePlane.cpp:26:10: fatal error: 
      'ext/alloc_traits.h' file not found
#include <ext/alloc_traits.h>                   // for __alloc_traits<>::val...
         ^~~~~~~~~~~~~~~~~~~~
```

I'm sure that I have NLopt installed. I have tried to reinstall NLopt manually (following [https://nlopt.readthedocs.io/en/latest/](https://nlopt.readthedocs.io/en/latest/) ), and  using `brew install nlopt`. The error still exist. 

There is no error with the cmake command:
```
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "3.3.0") 
-- Found Boost: /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.66")  
-- Found GSL: /usr/local/Cellar/gsl/2.4/include (found suitable version "2.4", minimum required is "2.1") 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Doxygen need to be installed to generate the doxygen documentation
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/zhangyang/work/PhaseTracer/github_pt/BSMPT/build

```

I can compile BSMPT1 successfully on the same machine, and BSMPT2 on Ubuntu using similar procedure.

Could you help me on this?

Best, 
Yang Zhang

**Comment by phbasler** [comment]
Hi Yang, 

Sorry for the delay. 
I will have a look at this this week. 
Do you use the release version or the develop branch? 

Cheers
Philipp

**Comment by phbasler** [comment]
@phyzhangyang I created the branch CMake-error-Issue24 and changed the following things 
 - The utility library did not have the C++14 requirement. This should fix your first problem
 - I removed both ext/ includes. 
 - For the testing I changed the include of NLOpt to REQUIRED, so you will see if your NLOpt installation is found or not

Can you try it with the setup in that branch and tell me what happens?

Cheers
Philipp

**Comment by phyzhangyang** [comment]
Hi Philipp,

Thanks very much for your reply. 

The errors about C++14 and "ext/" have  been fixed on my mac. 

The screen outputs of CMake are

```
-- Found GSL: /usr/local/Cellar/gsl/2.4/include (found suitable version "2.4", minimum required is "2.1") 
-- Found NLopt: /usr/local/lib/libnlopt.dylib  
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
Doxygen need to be installed to generate the doxygen documentation
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/zhangyang/work/PhaseTracer/BSMPT/build 

```

There is still a make error

```
[  9%] Building CXX object src/minimizer/CMakeFiles/Minimizer.dir/Minimizer.cpp.o
In file included from /Users/zhangyang/work/PhaseTracer/BSMPT/src/minimizer/Minimizer.cpp:42:
/Users/zhangyang/work/PhaseTracer/BSMPT/include/BSMPT/minimizer/LibNLOPT/MinimizeNLOPT.h:6:10: fatal error: 
      'nlopt.hpp' file not found
#include <nlopt.hpp>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [src/minimizer/CMakeFiles/Minimizer.dir/Minimizer.cpp.o] Error 1
make[1]: *** [src/minimizer/CMakeFiles/Minimizer.dir/all] Error 2
make: *** [all] Error 2

```
Best, 
Yang

**Comment by phbasler** [comment]
Hi Yang, 

Good to know that at least those two are fixed. 

Is there a difference in Mac between the nlopt C and C++ installation? I encountered a similiar problem in the start because ubuntu has two different packages, libnlopt-dev and libnlopt-cxx-dev. Once I installed libnlopt-cxx it worked. Maybe the autocomplete on mac shows you some other packages once you type brew install nlopt and hit autocomplete.

If this is not the case, can you try again with the manual installation through cmake and make sure that the DNLOPT_CXX=ON is set? I think it should be the default.

Cheers 
Philipp

**Comment by phyzhangyang** [comment]
Hi Philipp,

DNLOPT_CXX=ON  is default in cmake of Nlopt. The screen outputs of installing Nlopt include nlopt.hpp:
```
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/pkgconfig/nlopt.pc
-- Installing: /usr/local/include/nlopt.h
-- Installing: /usr/local/include/nlopt.hpp
-- Installing: /usr/local/include/nlopt.f
...
```

I have just tried to add NLopt_INCLUDE_DIR to BSMPT/src/minimizer/CMakeLists.txt
```
if(NLopt_FOUND)
  target_link_libraries(Minimizer PUBLIC nlopt)
  target_include_directories(Minimizer PUBLIC ${NLopt_INCLUDE_DIR})
endif()
```
It seems to fix the problem. 

However, the error about "ext/"  appears again:
```
[ 30%] Building CXX object src/models/CMakeFiles/Models.dir/ClassTemplate.cpp.o
/Users/zhangyang/work/PhaseTracer/BSMPT/src/models/ClassTemplate.cpp:20:10: fatal error: 
      'ext/alloc_traits.h' file not found
#include <ext/alloc_traits.h>               // for __alloc_traits<>::value_type
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/models/CMakeFiles/Models.dir/ClassTemplate.cpp.o] Error 1
make[1]: *** [src/models/CMakeFiles/Models.dir/all] Error 2
make: *** [all] Error 2
```

Best, 
Yang

**Comment by phbasler** [comment]
Hi Yang, 

@jwittbrodt pointed out a mistake I did with the NLopt cmake setup. The FindNLopt.cmake file is not needed anymore (for at least ~3 years) as installing NLopt also installs the cmake files. I removed it and now it should work. 
I also found 3 more references of ext/ and removed those.
Can you try it again please and tell me if it works?

Cheers
Philipp

**Comment by phyzhangyang** [comment]
Hi Philipp,

A new error of executing cmake appears:

```
-- Configuring done
CMake Error at src/models/CMakeLists.txt:34 (add_library):
  Cannot find source file:

    /Users/zhangyang/work/PhaseTracer/BSMPT/include/BSMPT/models/ClassPotentialJonasSUSY.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at src/models/CMakeLists.txt:34 (add_library):
  No SOURCES given to target: Models

CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Best, Yang

**Comment by phbasler** [comment]
Sorry, some temporary stuff got mixed up in there. I removed it and now it builds again without those files

**Comment by phyzhangyang** [comment]
Now CMake works successfully, but Make gave: 
```
[ 61%] Building CXX object src/CMakeFiles/EWBGRenormScale.dir/prog/PlotEWBG_mu.cpp.o
/Users/zhangyang/work/PhaseTracer/BSMPT/src/prog/PlotEWBG_mu.cpp:25:10: fatal error: 
      'bits/exception.h' file not found
#include <bits/exception.h>                     // for exception
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/EWBGRenormScale.dir/prog/PlotEWBG_mu.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/EWBGRenormScale.dir/all] Error 2
make: *** [all] Error 2
```
There may be still some temporary stuff left?

**Comment by phbasler** [comment]
The ext/ and bits/ includes were generated by IWYU, but they are removed now

**Comment by phyzhangyang** [comment]
Everything works fine now. Thank you very much!

**Comment by phbasler** [comment]
Wonderful, thank you for your help. 

I will merge these changes to the master branch in a few hours and make a new mini release
