### ISSUE TITLE
CalculateEWBG spawns Bug on Mac

### ISSUE THREAD

**Issue by phbasler** [phbasler/BSMPT#27]
@slswilliamson reported that the command 
 
`./bin/CalculateEWBG --model=c2hdm --input=../example/C2HDM_Input.dat --output=testEWBG.csv --FirstLine=2 --LastLine=2 --config=../example/EWBG_config.txt --UseGSL=true —UseCMAES=true --UseNLopt=true `

yields

`Interrupted with error:
CalculateEWBG(5625,0x7fffc32333c0) malloc: *** error for object 0x7fc015500d10: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6`

The same bug does not appear on Ubuntu. 

First analys finds that this happens after the calculation of the wall.
This shall be investigated on the [MacBug](https://github.com/phbasler/BSMPT/tree/MacBug) branch

**Comment by phbasler** [comment]
@slswilliamson

Can you run the command 

'./bin/InvestigateMacBug --model=c2hdm --input=../example/C2HDM_Input.dat --output=test.csv --FirstLine=2 --LastLine=2 --config=../example/EWBG_config.txt --UseGSL=true --UseCMAES=true --UseNLopt=true'

and copy me the output?

**Comment by slswilliamson** [comment]
Hi @phbasler, 

This yields:

```
Staring init
Found the Wall thicknes at LW = 0.03379356762945173
Found minimum plane
Checking for complex phases
End init
InvestigateMacBug(15254,0x7fffcc9093c0) malloc: *** error for object 0x7f8ba2701750: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by phbasler** [comment]
@slswilliamson can you try it again please? I just fixed a small out of bounds error

**Comment by slswilliamson** [comment]
@phbasler: successful result!

Finished EWPT
Staring init
Found the Wall thicknes at LW = 0.03379356762945173
Found minimum plane
Checking for complex phases
End init
Succeded ? 1	 (1 = Success , -1 = v/T reached a value below 0.00000000000000000e+00 during the calculation) 
omega_c = 2.00796409661300260e+02 GeV
T_c = 1.45568847656250000e+02 GeV
xi_c = omega_c/T_c = 1.37939135257473522e+00
omega_CB(T_c) = -3.58511850711577129e-06 GeV
omega_1(T_c) = -4.99296662849083361e+01 GeV
omega_2(T_c) = -1.94485074000702468e+02 GeV
omega_CP(T_c) = 1.33512115093615047e+00 GeV
The Wall thickness is given by L_W  = 3.37935676294517304e-02GeV^-2
L_W * T = 4.91929069801284058e+00
eta_TopOnly = -3.32805958926340651e-11
eta_TopBot = -3.33836515625869763e-11
eta_TopBotTau = -3.33832152435722752e-11
eta_PlasmaVelocities = -4.54025619036961021e-13
eta_PlasmaVelocitiesReplaced = -3.36861663801083807e-13
