### ISSUE TITLE
C2HDM/N2HDM tests fail

### ISSUE THREAD

**Issue by jwittbrodt** [phbasler/BSMPT#41]
Hi guys,

the C2HDM and  RN2HDM tests fail for me using the latest master using
 - gcc 11.1
 - eigen 3.3.9
 - gsl 2.7
 - boost 1.75.0
and the default libcmaes.

The tests pass in the CI, so this has to be something about newer compiler/library versions.

I get the following output for the failed tests in the C2HDM
```
[ctest] -------------------------------------------------------------------------------
[ctest] Checking EWPT for C2HDM
[ctest] -------------------------------------------------------------------------------
[ctest] ../tests/Test-c2hdm.cpp:48
[ctest] ...............................................................................
[ctest] 
[ctest] ../tests/Test-c2hdm.cpp:77: FAILED:
[ctest]   REQUIRE( std::abs(res - expected) / expected <= 1e-4 )
[ctest] with expansion:
[ctest]   0.4644279569 <= 0.0001
[ctest] with messages:
[ctest]   Current Option for Minimizer:	3
[ctest]   This ist the position:0	Found solution =5.72291e-06	Expected solution = -1.
[ctest]   06856e-05
```
and N2HDM
```
[ctest] -------------------------------------------------------------------------------
[ctest] Checking EWPT for N2HDM
[ctest] -------------------------------------------------------------------------------
[ctest] ../tests/Test-rn2hdm.cpp:52
[ctest] ...............................................................................
[ctest] 
[ctest] ../tests/Test-rn2hdm.cpp:81: FAILED:
[ctest]   REQUIRE( std::abs(res - expected) / expected <= 1e-2 )
[ctest] with expansion:
[ctest]   0.072245168 <= 0.01
```

Cheers,
Jonas

p.s.: check out catch Approx

**Comment by mb-1054571971** [comment]
Hi!

I am having the same issues as @jwittbrodt . My setup is the following:
- gcc (Debian 8.3.0-6) 8.3.0
- eigen 3.3.9
- gsl 2.5
- boost 1.67.0.1
- default libcmaes

Running `ctest --output-on-failure`, the tests fail for C2HDM and N2HDM, with the following output:

*C2HDM:
`Checking EWPT for C2HDM
-------------------------------------------------------------------------------
../tests/Test-c2hdm.cpp:48
...............................................................................

../tests/Test-c2hdm.cpp:77: FAILED:
  REQUIRE( std::abs(res - expected) / expected <= 1e-4 )
with expansion:
  0.8093326294 <= 0.0001
with messages:
  Current Option for Minimizer:	3
  This ist the position:0	Found solution =2.0374e-06	Expected solution = -1.
  06856e-05
`

*N2HDM:
`Checking EWPT for N2HDM
-------------------------------------------------------------------------------
../tests/Test-rn2hdm.cpp:52
...............................................................................

../tests/Test-rn2hdm.cpp:81: FAILED:
  REQUIRE( std::abs(res - expected) / expected <= 1e-2 )
with expansion:
  0.657492402 <= 0.01
`

Thanks!

Mårten

**Comment by phbasler** [comment]
@jwittbrodt Your current option in the minimizer is 3, this means you don't have NLopt linked, just gsl and cmaes. The CI check uses all 3 of them, so that can lead to different numerical results. 
I will include an CI check without NLopt while looking into this.

**Comment by jwittbrodt** [comment]
works for me, thanks :+1:

**Comment by mb-1054571971** [comment]
Sorry, I realized I had forgotten to reply to this. 

It works for me also now. Thanks!
