### ISSUE TITLE
Usage of BRs in input

### ISSUE THREAD

**Issue by mbr-phys** [phbasler/BSMPT#43]
Hi, 

In example/R2HDM_Input.dat, you have the parameters of the 2HDM as input, but then also a series of BRs etc. This would seem to suggest that these are part of the input for the package.
If I use my own input file that only has the type, lambda_i, m12sq, tanbeta, the BSMPT executable runs fine.
As well if I look at sh/prepareData_R2HDM.py, then it wouldn't appear that all these extra values are needed; looking through the code and documentation for BSMPT I also can't see anything to suggest these are used at any point.

Is there some requirement for these BRs etc within BSMPT I am missing? 

Thanks

**Comment by phbasler** [comment]
Hi, 

Not at all. These output files were generated with ScannerS for our phenomenoligical papers. 
They were included to show that the new columns are added after all existing ones.

**Comment by mbr-phys** [comment]
Ok, thanks for the clarification!
